# Config for vserver
[Interface]
Address = 10.9.0.1/24, fd00:cafe:10::1
PrivateKey = XXXXXXXXXXXX
ListenPort = 51821

# Allow forwarding to/from the tunnel
PostUp = iptables -A FORWARD -i eth0 -o %i -d 10.9.0.2 -j ACCEPT
PostUp = iptables -A FORWARD -i %i -o eth0 -s 10.9.0.0/24 -j ACCEPT
PostUp = iptables -A FORWARD -i %i -o %i -s 10.9.0.0/24 -d 10.9.0.0/24 -j ACCEPT

PostUp = ip6tables -A FORWARD -i eth0 -o %i -d fd00:cafe:10::2 -j ACCEPT
PostUp = ip6tables -A FORWARD -i %i -o eth0 -s fd00:cafe:10::/48 -j ACCEPT
PostUp = ip6tables -A FORWARD -i %i -o %i -s fd00:cafe:10::/48 -d fd00:cafe:10::/48 -j ACCEPT
# Send incoming traffic on second ip to tunnel
PostUp = iptables -t nat -A PREROUTING -d 81.16.19.192 -j DNAT --to-destination 10.9.0.2
PostUp = ip6tables -t nat -A PREROUTING -d 2a03:4000:3e:20d:3410:ff:fe64:eec5 -j DNAT --to-destination fd00:cafe:10::2
# Send outgoing traffic from tunnel, change source to public ip
PostUp = iptables -t nat -A POSTROUTING -s 10.9.0.2 -d ::/0 -j SNAT --to-source 81.16.19.192
PostUp = ip6tables -t nat -A POSTROUTING -s fd00:cafe:10::2 -d ::/0 -j SNAT --to-source 2a03:4000:3e:20d:3410:ff:fe64:eec5

# Remove forwarding rules
PreDown = iptables -D FORWARD -i eth0 -o %i -d 10.9.0.2 -j ACCEPT
PreDown = iptables -D FORWARD -i %i -o eth0 -s 10.9.0.0/24 -j ACCEPT
PreDown = iptables -D FORWARD -i %i -o %i -s 10.9.0.0/24 -d 10.9.0.0/24 -j ACCEPT
PreDown = ip6tables -D FORWARD -i eth0 -o %i -d fd00:cafe:10::2 -j ACCEPT
PreDown = ip6tables -D FORWARD -i %i -o eth0 -s fd00:cafe:10::/48 -j ACCEPT
PreDown = ip6tables -D FORWARD -i %i -o %i -s fd00:cafe:10::/48 -d fd00:cafe:10::/48 -j ACCEPT

PreDown = iptables -t nat -D PREROUTING -d 81.16.19.192 -j DNAT --to-destination 10.9.0.2
PreDown = ip6tables -t nat -D PREROUTING -d 2a03:4000:3e:20d:3410:ff:fe64:eec5 -j DNAT --to-destination fd00:cafe:10::2
PreDown = iptables -t nat -D POSTROUTING -s 10.9.0.2 -d ::/0 -j SNAT --to-source 81.16.19.192
PreDown = ip6tables -t nat -D POSTROUTING -s fd00:cafe:10::2 -d ::/0 -j SNAT --to-source 2a03:4000:3e:20d:3410:ff:fe64:eec5


[Peer]
PublicKey = makOhc7RNsBxBcKGIR+kj+mg1ci8/u0eFVjDzX9qFX8=
AllowedIPs = 10.9.0.2/32, fd00:cafe:10::2
