# Config for k8s-client
[Interface]
Address = 10.9.0.2, fd00:cafe:10::2
PrivateKey = XXXXXXXXXXXX

[Peer]
Endpoint = [2a03:4000:3e:20d:3410:ff:fe64:eec4]:51821
PublicKey = 9fzlEiDqiXF+uKX2BhNc+QDB2bOfQwoX2u0SRmnbxyc=
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25

