---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: matrix-infrastructure
  namespace: flux-system
spec:
  providerRef:
    name: matrix-bot
  eventMetadata:
    summary: Production Infrastructure impacted
  eventSeverity: error
  eventSources:
    - kind: GitRepository
      name: flux-system
    - kind: Kustomization
      name: infra-crds
    - kind: Kustomization
      name: infra-controllers
    - kind: Kustomization
      name: infra-configs
  exclusionList:
    - ".*https://github\\.com.*TLS handshake timeout.*"
    - ".*https://github\\.com.*connection reset by peer.*"

---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: matrix-apps
  namespace: flux-system
spec:
  providerRef:
    name: matrix-bot
  eventMetadata:
    summary: Production Apps impacted
  eventSeverity: error
  eventSources:
    - kind: GitRepository
      name: "*"
    - kind: Kustomization
      name: "*"
    - kind: HelmRelease
      name: "*"
  exclusionList:
    - ".*flux-system.*"
