apiVersion: v1
kind: Secret
metadata:
    name: matrix-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:k/vNSdh9X2cMYSt185vRV2GzNBX+a2FGuH25KSHuN71Lz5NcTqMHcds=,iv:XSQMkyR9pKL8wNxnkrnq2CW2qFz8nV6KdKrmnvkY5bc=,tag:bsGkRtmPtq3uxTnfaaMYpQ==,type:str]
sops:
    age:
        - recipient: age1ks6lqquvmucdzlfsreh5swjhrd4q80wqk7ggpyuun4p5cf2uc3msuwfh7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3L3V4L0R6ZEtUTjVFUkRx
            ZktsYlhkeitZVmE4M0tmaEJ2aW0vcUJpZ3hzClhXNzRpNTljSm02TFN1T3FKMFdL
            WmtWOWtieG9XZ3pCNjZMMCt4eTVtaHcKLS0tIGI3M21vSlI2S2FKUUxpc25MaW5n
            Mzg3YjNLajFJTUZCNmliY1NlRVYwNjAK2DjyhnHXqdEauQdLyYSftaGpeKoQSewQ
            rliMSexx8mGsJ7MNvgLfoahGu7hJhxPwChszuP3ZXCEwdPIXWqFzpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T18:04:17Z"
    mac: ENC[AES256_GCM,data:WelRAeGA73X5IRMAP2a3nZSJpaOdHH2YJZxp4BkK6hdZWI+Zj3oenwQBG8cOo0CD22PffukYROVLSFnLiUus9j5g4qqgCnlkFg2PLGzp5SlGMLKckr9GmSLJ+gnD6jxNxE1hyqEdU+40xW23dxfLfqhwrxQ1CHo3qzcDlcrQ4z8=,iv:i8AydZeZq9O50Mc8j6SftbTCGu53nND07pvrlqbhNyI=,tag:ZNc6x/EYijojkX5I3/0O3A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
