# helm repo add docker-mailserver https://docker-mailserver.github.io/docker-mailserver-helm
# helm upgrade --install docker-mailserver docker-mailserver/docker-mailserver --namespace mail --create-namespace -f values.yaml
deployment:
  env:
   OVERRIDE_HOSTNAME: mail-test.doblerones.de

certificate: mail-test-cert

proxyProtocol:
  enabled: true
  # List of sources (in CIDR format, space-separated) to permit PROXY protocol from
  trustedNetworks: "10.0.0.0/8 192.168.0.0/16 172.16.0.0/16"

service:
  type: ClusterIP
