[Interface]
Address = 10.44.0.10/24
PrivateKey = <private_key>

Table = off
# When the tunnel comes up, create a custom routing table (ID 200)
# and force traffic from the bridge subnet to use it.
PostUp = ip rule add from 10.44.1.0/24 table 200
PostUp = ip route add default dev %i table 200


# Clean up when the tunnel goes down
PreDown = ip rule del from 10.44.1.0/24 table 200
PreDown = ip route del default dev %i table 200

[Peer]
Endpoint = venti.doblerones.de:51823
PublicKey = <peer_public_key>
AllowedIPs = 10.44.0.1/32, 0.0.0.0/0
PersistentKeepalive = 25