apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-vol-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-zfspv
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: storage-volume-test
  namespace: default
spec:
  restartPolicy: Always
  containers:
    - name: volume-test
      image: busybox:latest
      imagePullPolicy: IfNotPresent
      command:
        - sh
        - -c
        - |
          echo "PVC mounted successfully at $(date)" >> /data/pv-test.txt
          echo "ready"
          sleep infinity
      livenessProbe:
        exec:
          command:
            - test
            - -d
            - /data/
        initialDelaySeconds: 5
        periodSeconds: 10
      volumeMounts:
        - name: vol
          mountPath: /data
  volumes:
    - name: vol
      persistentVolumeClaim:
        claimName: storage-vol-pvc
