apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-tcp
spec:
  selector:
    matchLabels:
      app: debug-tcp
  template:
    metadata:
      labels:
        app: debug-tcp
    spec:
      containers:
      - name: debug-tcp
        image: debian
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        command: ["/bin/bash", "-c", "tail -f /dev/null"]
        ports:
        - containerPort: 587
---
apiVersion: v1
kind: Service
metadata:
  name: debug-tcp
spec:
  selector:
    app: debug-tcp
  ports:
  - port: 587
    targetPort: 587
