apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - kgateway.yaml
  - snapshot-controller.yaml
  - openebs.yaml
  - velero/velero.yaml
  - velero/velero-credentials.yaml
