---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/dms
patches:
  - path: dms/release-patch.yaml
    target:
      kind: HelmRelease
  - path: dms/cert-patch.yaml
    target:
      kind: Certificate
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - renovate/secret.yaml
  - ../base/renovate
