---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/dms

  - renovate/secret.yaml
  - ../base/renovate

  - ../base/bentopdf
patches:
  - path: dms/release-patch.yaml
    target:
      kind: HelmRelease
      namespace: dms
  - path: dms/cert-patch.yaml
    target:
      kind: Certificate
      namespace: dms
  - path: bentopdf/listenerset-patch.yaml
    target:
      kind: XListenerSet
      namespace: bentopdf
  - path: bentopdf/release-values-patch.yaml
    target:
      kind: HelmRelease
      namespace: bentopdf
  - path: bentopdf/cert-patch.yaml
    target:
      kind: Certificate
      namespace: bentopdf
