apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gateways.yaml
  - https_redirect.yaml
  - cluster-issuers.yaml
  - flux/notification-provider.yaml
  - flux/provider-secret.yaml
  - flux/alerts.yaml
