apiVersion: v1
kind: Secret
metadata:
    name: velero-credentials
    namespace: velero
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:biCNk2D8LS0e+arTP5J6bhtW8NMz+awmS/NQhUz7hdl6BCq35UA4ROf8tzxzbaYbBF82br+6TWnBkkYxOKQyIqx2ny+K/o8UOOoJrE0knolGBMsjPmcgywTKolNnpzEJogyHi7ID+O5sPmkq/2z67u4SzUltPkiKB0hkbmViFiHs10qsFtELObBXM1yR5HaIWmQ=,iv:A8ilU2vighHYTt9u1XInIflhdGhRKsD34QJozE5ZYFA=,tag:KLPAk77j94OMlFhantPs4w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NXZFaUg1dmF1dzlDeURM
            RDFReXNXbWFIYXI5azJRWFhRbkEyelhMUGhFCjgrS1FXTHhpRDhNR00zN01oR0Qy
            ZjNXclJTblh2WUFjVWI1YzRuN0dqTjQKLS0tIEwwUkdBL2lTT1RES1BjQW42TDRP
            WHdoUUJONE5mZ1MyUkNpZm9HQ29zNEUKRhyW2XouozcU+9VuK/jCxNRzihbjxmMr
            JKpy9s3lk7AlmlW6mn0wrQnnWWbqeb61T3I6UZFl9PWXxYGLItclxQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ks6lqquvmucdzlfsreh5swjhrd4q80wqk7ggpyuun4p5cf2uc3msuwfh7h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-29T16:43:49Z"
    mac: ENC[AES256_GCM,data:gZOTsBvjAt4xq2E7AcsY7I/VRyjZ8TwwSFxww8fRjThVrYcXyg2xX/TuE7Uwn8V9eSZyGK1GILEk2kFcgSGap+2jeN70nGeP13H1bMONJd6OAxah2APX+FOlp/faCRoh1sa0gS0+eQuKAuDnK4HZTl9o7sg2nKhd4mTN1V0CKVs=,iv:iDi0NrLB5ReS6ASzSqUDfD/yVGlivyEdseykBn/pZXQ=,tag:w6FzMZoRJjBS2kNYjDmmXw==,type:str]
    version: 3.13.2
