apiVersion: v1
kind: Secret
metadata:
    name: velero-credentials
    namespace: velero
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:CMKEHkqlcki0W5v1E70WK5lXlGkMaTsOFeVep2jah44AFWA97SDYZiPNeYwPekydNXaXK0I7KC+M5V3aTSZptRbeMj9I9c+TVAEEd/H6MLFEUT76qn7wfmBJ0ggLbMGgdot+mAF7LOn5a8y2AE+GHFMnPPF52zZ/Vj/aX0KlyJSbQO9n7lMrPfGtWGGpQtqtbZ4=,iv:b3Zj4AFwhbTBroUh74G+ircsWsAwD1zyR9ROjW61Ba8=,tag:56C+VORQzUiEqxt1ZrZCsw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NXZFaUg1dmF1dzlDeURM
            RDFReXNXbWFIYXI5azJRWFhRbkEyelhMUGhFCjgrS1FXTHhpRDhNR00zN01oR0Qy
            ZjNXclJTblh2WUFjVWI1YzRuN0dqTjQKLS0tIEwwUkdBL2lTT1RES1BjQW42TDRP
            WHdoUUJONE5mZ1MyUkNpZm9HQ29zNEUKRhyW2XouozcU+9VuK/jCxNRzihbjxmMr
            JKpy9s3lk7AlmlW6mn0wrQnnWWbqeb61T3I6UZFl9PWXxYGLItclxQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ks6lqquvmucdzlfsreh5swjhrd4q80wqk7ggpyuun4p5cf2uc3msuwfh7h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-21T15:44:07Z"
    mac: ENC[AES256_GCM,data:LjwQXCNy8EonoXSraMF/CYUfzdQGGBHVkprvN1yfsbefwZnAnOG/mnAC0znkx8G+pKbY71xq4oe7wBWhGLGQjaQnRkGlfcYEYrts4YOr5OoWxwEL5kp0/Qs83P18LsXc+xYZQSP+8iIsf1UNsBkZreyL/edsCENQ4t44ya6+XS8=,iv:McrTIut1lAXnyaX5lDPBTcLvLNTxXL30CVv+rzc73zY=,tag:F1xLhdQa9xHVFNW3E6e3mA==,type:str]
    version: 3.13.1
