apiVersion: v1
kind: Secret
metadata:
    name: velero-credentials
    namespace: velero
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:0Mz2o5glSulY/SkWMnxQVndGCm3y3dm/oTdnzd9okgd3SpW7DPFDm0RdYVSVq2g35RM0ExhWkJyuWlEzYiY/MRr1CXYEQAKtN7j3tOva70u0hDfTylg6PACPbKK5jVVvbI17u3x/AdykX77rE8AKrYysjiPYmm57PijvtoEDH4oJg7jdLIw8tLqytf5J/wra1rk=,iv:8OwpvgwggpRYWMVUOJrzrYVL3AU5KJ9JBK5q6AQia/w=,tag:9aLzp/D+8IcL19YJGlVuDQ==,type:str]
sops:
    age:
        - recipient: age1ks6lqquvmucdzlfsreh5swjhrd4q80wqk7ggpyuun4p5cf2uc3msuwfh7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NXZFaUg1dmF1dzlDeURM
            RDFReXNXbWFIYXI5azJRWFhRbkEyelhMUGhFCjgrS1FXTHhpRDhNR00zN01oR0Qy
            ZjNXclJTblh2WUFjVWI1YzRuN0dqTjQKLS0tIEwwUkdBL2lTT1RES1BjQW42TDRP
            WHdoUUJONE5mZ1MyUkNpZm9HQ29zNEUKRhyW2XouozcU+9VuK/jCxNRzihbjxmMr
            JKpy9s3lk7AlmlW6mn0wrQnnWWbqeb61T3I6UZFl9PWXxYGLItclxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-25T16:20:04Z"
    mac: ENC[AES256_GCM,data:UBPeALvsrrO559Y2klrufmxESC5Twx4Q8XmmFwjAw2VfN7vXjEZQbP8MpHRIXHIecJAbAP+OoHAQywY88wgjNi5wSthAOnJ0RgXBlALfJzbBXuNyFEueG8KlM32ROjSfwJRVzAx4DzD4sN4+fh5eOptF5ffWvnaLYg8MMnc4PeI=,iv:baIg9Q62meKkDJUO7Ik6ya2mHu3/ZILafTGG5sIX4Iw=,tag:nyWXnAPEdD7BNGowUwGMow==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.13.1
