# helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
# helm upgrade --install -n ingress-nginx --create-namespace ingress-nginx ingress-nginx/ingress-nginx -f values.yaml
# for now use my own changes using clusterIPs fix
######### helm upgrade --install -n ingress-nginx --create-namespace ingress-nginx ingress-nginx/ingress-nginx -f values.yaml
controller:
  service:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/loadBalancerIPs: 10.41.78.1,fd00:cafe:4178::1
    ipFamilies:
      - IPv6
      - IPv4
    ipFamilyPolicy: RequireDualStack
    # externalTrafficPolicy: Local
  config:
    enable-real-ip: "true"
    # use-proxy-protocol: "true"
    # set-real-ip-from: 
    # proxy-real-ip-cidr: "10."
  # extraArgs:
    # - --tcp-services-configmap=ingress-nginx/tcp-services

# tcp:
  # 465: "mail/docker-mailserver:10465:PROXY:PROXY"
  # 993: "mail/docker-mailserver:10993:PROXY:PROXY"
