# helm upgrade --install -n ingress-nginx --create-namespace ingress-nginx  -f values.yaml
# for now use my own changes using clusterIPs fix
######### helm upgrade --install -n ingress-nginx --create-namespace ingress-nginx ingress-nginx/ingress-nginx -f values.yaml
controller:
  service:
    type: ClusterIP
    clusterIPs: 
      - fd00:cafe:43::10
      - 10.43.1.1
    ipFamilies:
      - IPv6
      - IPv4
    ipFamilyPolicy: RequireDualStack
    externalIPs:
      - fd00:cafe:41::1
      - 10.9.0.2
      - fd00:cafe:10::2
      - 192.168.1.100
    externalTrafficPolicy: Local
  config:
    enable-real-ip: "true"
    # use-proxy-protocol: "true"
    # set-real-ip-from: 
    # proxy-real-ip-cidr: "10."
  # extraArgs:
    # - --tcp-services-configmap=ingress-nginx/tcp-services

tcp:
  465: "mail/docker-mailserver:10465:PROXY:PROXY"
  993: "mail/docker-mailserver:10993:PROXY:PROXY"
