---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restore-pvc
  namespace: storage-test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-zfspv
  dataSource:
    kind: VolumeSnapshot
    name: snapshot
    apiGroup: snapshot.storage.k8s.io
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: restore-workload
  namespace: storage-test
spec:
  restartPolicy: Always
  containers:
    - name: volume-test
      image: busybox:latest
      imagePullPolicy: IfNotPresent
      command:
        - sh
        - -c
        - |
          echo "ready"
          ls -la /data
          cat /data/pv-test.txt
          sleep infinity
      volumeMounts:
        - name: vol
          mountPath: /data
  volumes:
    - name: vol
      persistentVolumeClaim:
        claimName: restore-pvc
