# ❯ velero backup-location create -o yaml --default --bucket velero-backups --provider aws --config region=garage,s3ForcePathStyle=true,s3Url=https://test123:3900 default
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: velero
spec:
  provider: aws
  accessMode: ReadWrite
  default: true
  config:
    s3Url: https://s3.doblerones.de:3900
    region: garage
    s3ForcePathStyle: "true"
  objectStorage:
    bucket: velero-backups
