apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backupStorageLocation.yaml
  - volumeSnapshotLocation.yaml

configMapGenerator:
  - name: default-policy
    namespace: velero
    options:
      disableNameSuffixHash: true
    files:
      - defaultPolicy.yaml
