apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.yaml
  - ../../base/renovate
patches:
  - path: release-patch.yaml
    target:
      kind: HelmRelease
      namespace: renovate
