apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/renovate
patches:
  - path: release-patch.yaml
    target:
      kind: HelmRelease
      namespace: renovate
secretGenerator:
  - name: renovate-selfhosted-config
    namespace: renovate
    files:
      - config=config.enc
configurations:
  - secretNameReference.yaml
