apiVersion: v1
kind: Secret
metadata:
    name: renovate-selfhosted-config
    namespace: renovate
    labels:
        reconcile.fluxcd.io/watch: Enabled
type: Opaque
stringData:
    config: ENC[AES256_GCM,data:bgQ0JtAJp6fd7hzxvW6ZLYSOI1sDAX7qehpX2HSfbkQhT1Ih+isfH06oxkvM+l/Lb47NECeepjWPHFKrGJUurOcHy9mBlAD0OxiiCyxMILZTH98VAi098uXfy9p/Ik63dWAeXyV8HM1ZFmwyZ4etCGF/qDd9AWqKbFna88JSClXSWbwGsPtkNbM57a9g+tdnGjcPae+ZA6KhEPLjTD+V+CJUgbYEF2rOy7t1mcJjJ8XNBAw7HyQlHb5F1/bbTFSOT7FWH+QvEOIO4Yu97yOWUtojkZ2G,iv:iayV2QhXPjaZrNV1bgYGYxbfXH3B6Qxh2de4vy9qqCs=,tag:74OnwGxeiVMYmvKFrMTAfQ==,type:str]
sops:
    age:
        - recipient: age1ks6lqquvmucdzlfsreh5swjhrd4q80wqk7ggpyuun4p5cf2uc3msuwfh7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhaTQ4RkVzbmFCaTNzdWpt
            N1VNQWZZMkxWV24wVlViUVNOZFh2MXNLWTBVClFQZHpTZG8rbSt2eDFOdVdEVnNU
            RmNPSitWYjJhbmZWL2VaKzNnU1NYWkUKLS0tIElSdGZWeEhqTThOS01CWndQRDBO
            Z3BuQlhGdjBnRWtHUGJOcGlGWDFqaW8KEsJOU/BrffMlZLwQy+OEFxC5+ANKw2mv
            KslQ5u7TerMJfmtSBqYyVYtfvcbgin1vnc4I06m31noslgTduHTfVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-08T20:45:28Z"
    mac: ENC[AES256_GCM,data:ZXfU9KsQpDbsiEqBIpPdffyS8p7ub0n3YXaUinsYAqh6iRxRL/O807SkGm1FnF3+j6gBqQMEuXjuPJ1sHrXWGN159CBC4PwHDUlfFkAYrHHwkO5FxTbNCamdlKzQKKwKTTsnkCR0EzbkExTU9qfqLeXWuWjslwNrTwGNDlzKJ64=,iv:poNHCsDVbEuEC9WAbWCJfjNIE4Mcn3fEPmc3hAaqHeQ=,tag:pjdyWyrbdOTNFJgMQd1Rgw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
