apiVersion: v1
kind: Secret
metadata:
    name: renovate-selfhosted-config
    namespace: renovate
type: Opaque
stringData:
    config: ENC[AES256_GCM,data:naQqYMnzsYzv165mOrze7boVq5BY1BcIlCuIXBogj/eYWzkBlTRYM3uETN3sVJgQMatym/36j3byuUIoNHtAkK0u/wpfssAT8oYbShbgnGwL2IetydxBw33q9Vhx1Bzr3oDb8RwRJzQRJflBkpXrXiw+9dJir2iFyv0fDLVctUdaV7MMoVuLTe3MduirNNtgwt/KuEfIFN8LlcJ2ss+TOYG/,iv:d+mLoBKmOXqY2dITK+2GoZJwTYgThnlX3jsA5NnWuPY=,tag:mM17jEuNMFwC5VEnIKYTaw==,type:str]
sops:
    age:
        - recipient: age1ks6lqquvmucdzlfsreh5swjhrd4q80wqk7ggpyuun4p5cf2uc3msuwfh7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhaTQ4RkVzbmFCaTNzdWpt
            N1VNQWZZMkxWV24wVlViUVNOZFh2MXNLWTBVClFQZHpTZG8rbSt2eDFOdVdEVnNU
            RmNPSitWYjJhbmZWL2VaKzNnU1NYWkUKLS0tIElSdGZWeEhqTThOS01CWndQRDBO
            Z3BuQlhGdjBnRWtHUGJOcGlGWDFqaW8KEsJOU/BrffMlZLwQy+OEFxC5+ANKw2mv
            KslQ5u7TerMJfmtSBqYyVYtfvcbgin1vnc4I06m31noslgTduHTfVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-07T01:41:24Z"
    mac: ENC[AES256_GCM,data:aQrpfoUKbvA5efzG8GqOfA+XilWM38jCtFFN/WM6lKPLFKzrrU0AzfWOgTIyT33OOg3M1vY7quKcS2RiHR7P6wDop9TiQffwmamax7ePJAAVvVZ9ia+Re1WwEuUk7MoRjXMW0ilD5uCo8YqEN3aQOFidb0zu8/DQx+sxOWcweDQ=,iv:DtBqSBhBkvtck51Uquq6uOCQNIXDiu/V+uxKgJkjotw=,tag:FPpCNVyhemxrACWyY5fS0g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
