apiVersion: v1
kind: Secret
metadata:
    name: renovate-selfhosted-config
    namespace: renovate
    labels:
        reconcile.fluxcd.io/watch: Enabled
type: Opaque
stringData:
    config: ENC[AES256_GCM,data:nIZB6uM/a0QW9dwCsXt+dZMnpzk/9VTHa8zIY2s2pLEqLaQBs5m+UlRouEoYhmR3Vablie9hN3nrGjCnfdpyYE6nHPkwX8eyZVL8tPhoBAIrZ07K/R2Wal2/D/0a1Tr6gVH2r9GyMdQLp1963CJeEL/j8AnHeoc2M+zTj7pVt7CpS4B3lNLwn0hCcEpVTZ87aIC18/gJ+ic6BB7GXfDzhkEiVYyA/kHlj92yCvbUraakDNoYusjv+l+A/c8dbM8asrSlu1WX174RmEsrjT3bHD4rC57HmoTeiBiyu5fJPztoX7OsJBKBkwGm3HwxnZk1P/TlTNd+56vYDnjbOeTonqhz2R1C5NEsmnExXyhw5FxRmyLVn4+okJSCxP0uUKpfnxI9WTwGR2dqYCs0qg4KYDEFg4Wv6mQrgX8ys3ofq18saoE/2bKVZv0vwq8pAPbA+F+hu0qDCZw8Z8LX+lcpJe0Pywn1ncpvc1Per2K5T2I9io5bqoMsSt4rTdaXOJOQjBe03zF4BZUr/Rd7a6bg08+2Z/Q2mzy33i5VOczgSE4IO5ZP2+ilPRIksMlwB5XAMbIdZXr6FbUMZccg4qwVJ5G+tbHW0oyP5/JRq9Mq9NAF1BxlgZW2KPWd6sSezpxF3A1H0AHRCsWT51uGorNqj45FOu1BaqXwicsBeTsKloGapatZcBQlX0j8Pmw0vSrr8X9sy11jNJsyhQdmIZY0ZI6lPDHx2DJJLGNvq6oqfl/tD4BpWpyguhSZfqFG4T/B95ualg2yVVTmZO/1NLufwNEGPhhaYd55NMj7RRLejsxsz3q9gZluf0OiWyn9I9pQ8UT3HKUFaoyY7LqbFZhJHJnYqkN79nhattqtt7S3THl7dEleyk58U19F0m+B3C5dwHgYmJBmG+Bx3p9VwULhhw4pUg0fNpc6taN+rWF+9WW3jviIuZYFf+DMV9YVeQM/+mYSvEtJeXzV7XLCpSm4/QQ8RCOttxiH2wMlrW5TrgZA/fl7VAnFeSa2LaE1cMs7rwTSrjowBP7mMx54HfL58/aunh2Quve1AmdkxjXJ+oIWIn19UIgZY9VHSU+O5R8qrHqC8LAr0a8ips8n4qbjyEcG1Do1pWnPSOSEs07aww4kXoyAjUNSWi8h3y13P4bpVZZcJUQg6tv9gX5g7L3mz+KF4nHSO2tq71aUwdg6b8YPqmMwQpv+izFkzfgjP1JNh+zpu6DZVbLVX50ztixbUEutsHhDXuW1aj/d1Vjh4kvIKNrxJ0IbnBvmQhBloT4IW2AEloytUW/J8u98x8zJppD/MEro61+T0aVZ/IunMvIrFWq/RXc+0ug/vK3u5nG6ghzuZqoA6S3NqO6j04YQQSwE9U1VjhGIFbTXdHDiotqe4q00cvsOpbCpSbwA1MVFBKQWkxGo+P5tNEZw8WTT0ca5uhSIWjfi6YNMOE43z/6HDP7JEr9lje43xTleLt/eHqCW1Cw222KXYmIfnlFNw4+lvBzfsC80jrj7p4uerf74zfvHdDfTwwnN,iv:ZyxUUR7Vco5hFcJAPZAFTN9eV9bdwSxR6AW4UmhdnFk=,tag:WM0BS4RNWQ5f4iuVxoOCnQ==,type:str]
sops:
    age:
        - recipient: age1ks6lqquvmucdzlfsreh5swjhrd4q80wqk7ggpyuun4p5cf2uc3msuwfh7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhaTQ4RkVzbmFCaTNzdWpt
            N1VNQWZZMkxWV24wVlViUVNOZFh2MXNLWTBVClFQZHpTZG8rbSt2eDFOdVdEVnNU
            RmNPSitWYjJhbmZWL2VaKzNnU1NYWkUKLS0tIElSdGZWeEhqTThOS01CWndQRDBO
            Z3BuQlhGdjBnRWtHUGJOcGlGWDFqaW8KEsJOU/BrffMlZLwQy+OEFxC5+ANKw2mv
            KslQ5u7TerMJfmtSBqYyVYtfvcbgin1vnc4I06m31noslgTduHTfVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T14:51:04Z"
    mac: ENC[AES256_GCM,data:Eis8waCaSC3xkbwGDQ7iyKoh15TX/TVdFEX8ukuu4+rdkkrvxoKFjlPC7OlKz6Uu9GiCvh+i081pkNHUuXRB6z/5XHs8pbwC5chVCWzwXJcTghy5WgRzryq/lDGE1Zlb1KCT5oeKL0eocj1zcgT63Qu1M8hMBvEj0ND/ZwmL8ow=,iv:fNCBS2xKgvpVU0/Ky8AfCwFuTk0TWZMUs9izbClB/n8=,tag:k/C2oNvK/Qog+8b/2TbYQQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
